/* UI strings */
const I18N = {
  ar: {
    "title": "أداة الترقية - Hay Day",
    "subtitle": "خطط واحسب العناصر المطلوبة لترقية سعتك التالية.",
    "tabs.barn": "الحظيرة",
    "tabs.silo": "الصومعة",
    "tabs.expansion": "التوسعة",
    "materials.title": "المواد",
    "materials.hint.barn": "الحظيرة: مسمار ملولب، لوح خشبي، شريط لاصق قماشي.",
    "materials.hint.silo": "الصومعة: مسمار، برغي، لوح خشبي.",
    "materials.hint.expansion": "التوسعة: صك ملكية، مطرقة خشبية، وتد تحديد.",
    "materials.target": "السعة المستهدفة",
    "materials.target_ph": "مثال: 1000 أو 1050",
    "materials.targetTool": "الأداة المستهدفة",
    "materials.target_ph_exp": "مثال: 45",
    "materials.initial": "المخزون الأولي:",
    "materials.stock_ph": "أدخل النموذج لتنفيذ التوزيع",
    "btn.calculate": "احسب",
    "btn.clear": "مسح",
    "btn.clear_tip": "مسح جميع الحقول",
    "btn.preset": "مثال",
    "btn.preset_tip": "مثال سريع",
    "kpi.perTool": "الهدف لكل أداة:",
    "kpi.balanced": "متوازن ✓",
    "kpi.cap": "≤ 89/يوم ✓",
    "plan.title": "خطة التوزيع",
    "plan.hint": "خانات التوزيع اليومية + التتبع اليومي. الأعداد في نهاية اليوم متساوية تمامًا.",
    "plan.day": "يوم",
    "plan.used": "المستخدم",
    "plan.endTotal": "المجموع النهائي",
    "plan.each": "كل",
    "plan.sectionSlots": "📦 خانات التوزيع",
    "plan.sectionTracking": "📊 التتبع اليومي (متوازن في نهاية كل يوم)",
    "plan.policy": "حماية السياسة: إذا كان أي نموذج للمخزون الأولي فارغًا، فلن يتم تنفيذ أي توزيع؛ يتم عرض متطلبات كل أداة فقط.",
    "table.slot": "خانة",
    "table.tool": "أداة",
    "table.amount": "الكمية",
    "table.total": "الإجمالي",
    "table.start": "البداية",
    "table.added": "المضاف",
    "table.remaining": "المتبقي",
    "table.target": "الهدف",
    "table.check": "تحقق",
    "table.noDist": "لا يوجد توزيع",
    "err.invalid": "غير صالح! يرجى إدخال النموذج للمتابعة.",
    "msg.enter": "أدخل المخزون الأولي لتنفيذ التوزيع.",
    "msg.expansionReq": "تتطلب كل أداة <b>{n} عنصرًا</b> لفتح الأرض.",
    "msg.upgradeReq": "تتطلب كل أداة <b>{n} عنصرًا</b> للترقية من السعة {cap}.",
    "msg.generated": "تم إنشاء الخطة في {d} يوم (أيام). متوازنة يوميًا."
  },
  zh_CN: {
    "title": "升级工具 - Hay Day",
    "subtitle": "计划并计算您下一次容量升级所需的物品。",
    "tabs.barn": "谷仓",
    "tabs.silo": "筒仓",
    "tabs.expansion": "扩建",
    "materials.title": "材料",
    "materials.hint.barn": "谷仓：螺栓、木板、布基胶带。",
    "materials.hint.silo": "筒仓：钉子、螺丝、木制面板。",
    "materials.hint.expansion": "扩建：地契、木槌、标志桩。",
    "materials.target": "目标容量",
    "materials.target_ph": "例如 1000 或 1050",
    "materials.targetTool": "目标工具",
    "materials.target_ph_exp": "例如 45",
    "materials.initial": "初始库存：",
    "materials.stock_ph": "填写表单以执行分配",
    "btn.calculate": "计算",
    "btn.clear": "清除",
    "btn.clear_tip": "清除所有字段",
    "btn.preset": "预设",
    "btn.preset_tip": "快速示例",
    "kpi.perTool": "每种工具的目标：",
    "kpi.balanced": "已平衡 ✓",
    "kpi.cap": "≤ 89/天 ✓",
    "plan.title": "分配计划",
    "plan.hint": "每日分配槽 + 每日跟踪。每日结束时的数量完全相等。",
    "plan.day": "天",
    "plan.used": "已用",
    "plan.endTotal": "最终总计",
    "plan.each": "每个",
    "plan.sectionSlots": "📦 分配槽",
    "plan.sectionTracking": "📊 每日跟踪（每天结束时平衡）",
    "plan.policy": "策略保护：如果任何初始库存表单为空，则不执行分配；仅显示每种工具的要求。",
    "table.slot": "槽位",
    "table.tool": "工具",
    "table.amount": "数量",
    "table.total": "总计",
    "table.start": "开始",
    "table.added": "已添加",
    "table.remaining": "剩余",
    "table.target": "目标",
    "table.check": "检查",
    "table.noDist": "无分配",
    "err.invalid": "无效！请输入表单以继续。",
    "msg.enter": "输入初始库存以执行分配。",
    "msg.expansionReq": "每种工具需要 <b>{n} 个物品</b>来解锁土地。",
    "msg.upgradeReq": "每种工具需要 <b>{n} 个物品</b>从容量 {cap} 升级。",
    "msg.generated": "计划在 {d} 天内生成。每日平衡。"
  },
  zh_TW: {
    "title": "升級工具 - Hay Day",
    "subtitle": "計劃並計算您下一次容量升級所需的物品。",
    "tabs.barn": "穀倉",
    "tabs.silo": "筒倉",
    "tabs.expansion": "擴建",
    "materials.title": "材料",
    "materials.hint.barn": "穀倉：螺栓、木板、布基膠帶。",
    "materials.hint.silo": "筒倉：釘子、螺絲、木製面板。",
    "materials.hint.expansion": "擴建：地契、木槌、標記樁。",
    "materials.target": "目標容量",
    "materials.target_ph": "例如 1000 或 1050",
    "materials.targetTool": "目標工具",
    "materials.target_ph_exp": "例如 45",
    "materials.initial": "初始庫存：",
    "materials.stock_ph": "填寫表單以執行分配",
    "btn.calculate": "計算",
    "btn.clear": "清除",
    "btn.clear_tip": "清除所有欄位",
    "btn.preset": "預設",
    "btn.preset_tip": "快速範例",
    "kpi.perTool": "每種工具的目標：",
    "kpi.balanced": "已平衡 ✓",
    "kpi.cap": "≤ 89/天 ✓",
    "plan.title": "分配計劃",
    "plan.hint": "每日分配槽 + 每日追蹤。每日結束時的數量完全相等。",
    "plan.day": "天",
    "plan.used": "已用",
    "plan.endTotal": "最終總計",
    "plan.each": "每個",
    "plan.sectionSlots": "📦 分配槽",
    "plan.sectionTracking": "📊 每日追蹤（每天結束時平衡）",
    "plan.policy": "策略保護：如果任何初始庫存表單為空，則不執行分配；僅顯示每種工具的要求。",
    "table.slot": "槽位",
    "table.tool": "工具",
    "table.amount": "數量",
    "table.total": "總計",
    "table.start": "開始",
    "table.added": "已新增",
    "table.remaining": "剩餘",
    "table.target": "目標",
    "table.check": "檢查",
    "table.noDist": "無分配",
    "err.invalid": "無效！請輸入表單以繼續。",
    "msg.enter": "輸入初始庫存以執行分配。",
    "msg.expansionReq": "每種工具需要 <b>{n} 個物品</b>來解鎖土地。",
    "msg.upgradeReq": "每種工具需要 <b>{n} 個物品</b>從容量 {cap} 升級。",
    "msg.generated": "計劃在 {d} 天內生成。每日平衡。"
  },
  da: {
    "title": "Opgraderingsværktøj - Hay Day",
    "subtitle": "Planlæg og beregn de nødvendige genstande til din næste kapacitetsopgradering.",
    "tabs.barn": "LADE",
    "tabs.silo": "SILO",
    "tabs.expansion": "UDVIDELSE",
    "materials.title": "Materialer",
    "materials.hint.barn": "Lade: Bolt, Planke, Gaffatape.",
    "materials.hint.silo": "Silo: Søm, Skrue, Træpanel.",
    "materials.hint.expansion": "Udvidelse: Skøde, Træhammer, Markeringspæl.",
    "materials.target": "Målkapacitet",
    "materials.target_ph": "f.eks. 1000 eller 1050",
    "materials.targetTool": "Målværktøj",
    "materials.target_ph_exp": "f.eks. 45",
    "materials.initial": "Startlager:",
    "materials.stock_ph": "indtast formularen for at udføre distribution",
    "btn.calculate": "Beregn",
    "btn.clear": "Ryd",
    "btn.clear_tip": "Ryd alle felter",
    "btn.preset": "Eksempel",
    "btn.preset_tip": "Hurtigt eksempel",
    "kpi.perTool": "Mål pr. værktøj:",
    "kpi.balanced": "Afbalanceret ✓",
    "kpi.cap": "≤ 89/dag ✓",
    "plan.title": "Distributionsplan",
    "plan.hint": "Daglige distributionsslots + daglig sporing. Optællinger ved dagens slutning er nøjagtigt ens.",
    "plan.day": "Dag",
    "plan.used": "Brugt",
    "plan.endTotal": "Sluttotal",
    "plan.each": "hver",
    "plan.sectionSlots": "📦 Distributionsslots",
    "plan.sectionTracking": "📊 Daglig sporing (Afbalanceret ved slutningen af hver dag)",
    "plan.policy": "Politikbeskyttelse: hvis en startlagerformular er blank, udføres ingen distribution; kun kravene pr. værktøj vises.",
    "table.slot": "Slot",
    "table.tool": "Værktøj",
    "table.amount": "Antal",
    "table.total": "TOTAL",
    "table.start": "Start",
    "table.added": "Tilføjet",
    "table.remaining": "Resterende",
    "table.target": "Mål",
    "table.check": "Tjek",
    "table.noDist": "Ingen distribution",
    "err.invalid": "Ugyldig! Indtast venligst formularen for at fortsætte.",
    "msg.enter": "Indtast startlageret for at udføre distribution.",
    "msg.expansionReq": "Hvert værktøj kræver <b>{n} genstande</b> for at låse op for jorden.",
    "msg.upgradeReq": "Hvert værktøj kræver <b>{n} genstande</b> for at opgradere fra kapacitet {cap}.",
    "msg.generated": "Plan genereret på {d} dag(e). Afbalanceret dagligt."
  },
  de: {
    "title": "Upgrade-Werkzeug - Hay Day",
    "subtitle": "Plane und berechne die für dein nächstes Kapazitätsupgrade benötigten Gegenstände.",
    "tabs.barn": "SCHEUNE",
    "tabs.silo": "SILO",
    "tabs.expansion": "ERWEITERUNG",
    "materials.title": "Materialien",
    "materials.hint.barn": "Scheune: Bolzen, Brett, Panzerband.",
    "materials.hint.silo": "Silo: Nagel, Schraube, Holzpaneel.",
    "materials.hint.expansion": "Erweiterung: Landurkunde, Holzhammer, Markierungspfahl.",
    "materials.target": "Zielkapazität",
    "materials.target_ph": "z.B. 1000 oder 1050",
    "materials.targetTool": "Zielwerkzeug",
    "materials.target_ph_exp": "z.B. 45",
    "materials.initial": "Anfangsbestand:",
    "materials.stock_ph": "Formular zur Verteilung eingeben",
    "btn.calculate": "Berechnen",
    "btn.clear": "Löschen",
    "btn.clear_tip": "Alle Felder löschen",
    "btn.preset": "Beispiel",
    "btn.preset_tip": "Schnelles Beispiel",
    "kpi.perTool": "Ziel pro Werkzeug:",
    "kpi.balanced": "Ausgeglichen ✓",
    "kpi.cap": "≤ 89/Tag ✓",
    "plan.title": "Verteilungsplan",
    "plan.hint": "Tägliche Verteilungs-Slots + tägliche Verfolgung. Die Zählung am Ende des Tages ist genau gleich.",
    "plan.day": "Tag",
    "plan.used": "Verwendet",
    "plan.endTotal": "Endsumme",
    "plan.each": "jeweils",
    "plan.sectionSlots": "📦 Verteilungs-Slots",
    "plan.sectionTracking": "📊 Tägliche Verfolgung (Am Ende jedes Tages ausgeglichen)",
    "plan.policy": "Richtlinienschutz: Wenn ein Formular für den Anfangsbestand leer ist, wird keine Verteilung ausgeführt; nur die Anforderungen pro Werkzeug werden angezeigt.",
    "table.slot": "Slot",
    "table.tool": "Werkzeug",
    "table.amount": "Menge",
    "table.total": "GESAMT",
    "table.start": "Start",
    "table.added": "Hinzugefügt",
    "table.remaining": "Verbleibend",
    "table.target": "Ziel",
    "table.check": "Prüfen",
    "table.noDist": "Keine Verteilung",
    "err.invalid": "Ungültig! Bitte das Formular zur Durchführung eingeben.",
    "msg.enter": "Gib den Anfangsbestand ein, um die Verteilung durchzuführen.",
    "msg.expansionReq": "Jedes Werkzeug benötigt <b>{n} Gegenstände</b>, um das Land freizuschalten.",
    "msg.upgradeReq": "Jedes Werkzeug benötigt <b>{n} Gegenstände</b>, um von Kapazität {cap} aufzurüsten.",
    "msg.generated": "Plan in {d} Tag(en) erstellt. Täglich ausgeglichen."
  },
  en: {
    "title": "Upgrade Tool - Hay Day",
    "subtitle": "Plan and calculate the items required for your next capacity upgrade.",
    "tabs.barn": "BARN",
    "tabs.silo": "SILO",
    "tabs.expansion": "EXPANSION",
    "materials.title": "Materials",
    "materials.hint.barn": "Barn: Bolt, Plank, Duct Tape.",
    "materials.hint.silo": "Silo: Nail, Screw, Wood Panel.",
    "materials.hint.expansion": "Expansion: Land Deed, Mallet, Marker Stake.",
    "materials.target": "Target Capacity",
    "materials.target_ph": "e.g., 1000 or 1050",
    "materials.targetTool": "Target tool",
    "materials.target_ph_exp": "e.g., 45",
    "materials.initial": "Initial Stock:",
    "materials.stock_ph": "enter the form to perform distribution",
    "btn.calculate": "Calculate",
    "btn.clear": "Clear",
    "btn.clear_tip": "Clear all fields",
    "btn.preset": "Preset",
    "btn.preset_tip": "Quick example",
    "kpi.perTool": "Per-tool target:",
    "kpi.balanced": "Balanced ✓",
    "kpi.cap": "≤ 89/day ✓",
    "plan.title": "Distribution Plan",
    "plan.hint": "Daily distribution slots + daily tracking. End-of-day counts are exactly equal.",
    "plan.day": "Day",
    "plan.used": "Used",
    "plan.endTotal": "End total",
    "plan.each": "each",
    "plan.sectionSlots": "📦 Distribution Slots",
    "plan.sectionTracking": "📊 Daily Tracking (Balanced by the end of each day)",
    "plan.policy": "Policy guard: if any initial stock form is blank, no distribution is executed; only per-tool requirements are shown.",
    "table.slot": "Slot",
    "table.tool": "Tool",
    "table.amount": "Amount",
    "table.total": "TOTAL",
    "table.start": "Start",
    "table.added": "Added",
    "table.remaining": "Remaining",
    "table.target": "Target",
    "table.check": "Check",
    "table.noDist": "No distribution",
    "err.invalid": "Invalid! Please enter the form to perform.",
    "msg.enter": "Enter the initial stock to perform distribution.",
    "msg.expansionReq": "Each tool requires <b>{n} items</b> to unlock the land.",
    "msg.upgradeReq": "Each tool requires <b>{n} items to upgrade from capacity {cap}.</b>",
    "msg.generated": "Plan generated in {d} day(s). Balanced daily."
  },
  es: {
    "title": "Planificador de Mejora - Hay Day",
    "subtitle": "Planifica y calcula los artículos necesarios para tu próxima mejora de capacidad.",
    "tabs.barn": "GRANERO",
    "tabs.silo": "SILO",
    "tabs.expansion": "EXPANSIÓN",
    "materials.title": "Materiales",
    "materials.hint.barn": "Granero: Perno, Tabla, Cinta americana.",
    "materials.hint.silo": "Silo: Clavo, Tornillo, Panel de madera.",
    "materials.hint.expansion": "Expansión: Escritura de tierras, Mazo de madera, Estaca de marcar.",
    "materials.target": "Capacidad objetivo",
    "materials.target_ph": "p. ej., 1000 o 1050",
    "materials.targetTool": "Herramienta objetivo",
    "materials.target_ph_exp": "p. ej., 45",
    "materials.initial": "Existencias iniciales",
    "materials.stock_ph": "Ingrese el formulario para realizar la distribución.",
    "btn.calculate": "Calcular",
    "btn.clear": "Limpiar",
    "btn.clear_tip": "Limpiar el formulario",
    "btn.preset": "Ejemplo",
    "btn.preset_tip": "Ejemplo rápido",
    "kpi.perTool": "Objetivo por herramienta:",
    "kpi.balanced": "Igual ✓",
    "kpi.cap": "≤ 89/día ✓",
    "plan.title": "Plan de Distribución",
    "plan.hint": "Slots diarios y seguimiento. Los totales al final del día son iguales.",
    "plan.day": "Día",
    "plan.used": "Usado",
    "plan.endTotal": "Total final",
    "plan.each": "cada",
    "plan.sectionSlots": "📦 Ranuras de distribución",
    "plan.sectionTracking": "📊 Seguimiento diario (Equilibrado al final de cada día)",
    "plan.policy": "Protección de política: si algún formulario de existencias iniciales está en blanco, no se ejecuta la distribución; solo se muestran los requisitos por herramienta.",
    "table.slot": "Casilla",
    "table.tool": "Herramienta",
    "table.amount": "Cantidad",
    "table.total": "TOTAL",
    "table.start": "Inicio",
    "table.added": "Añadido",
    "table.remaining": "Restante",
    "table.target": "Objetivo",
    "table.check": "Verificación",
    "table.noDist": "Sin distribución",
    "err.invalid": "Inválido! Ingrese el campo para continuar.",
    "msg.enter": "Ingrese el stock inicial para ejecutar la distribución.",
    "msg.expansionReq": "Cada herramienta requiere <b>{n} unidades</b> para desbloquear el tierra.",
    "msg.upgradeReq": "Cada herramienta requiere <b>{n} unidades</b> para mejorar desde capacidad {cap}.",
    "msg.generated": "Plan generado en {d} día(s). Balanceado diariamente."
  },
  fi: {
    "title": "Päivitystyökalu - Hay Day",
    "subtitle": "Suunnittele ja laske seuraavaan kapasiteettipäivitykseesi tarvittavat esineet.",
    "tabs.barn": "LATO",
    "tabs.silo": "SIILO",
    "tabs.expansion": "LAAJENNUS",
    "materials.title": "Materiaalit",
    "materials.hint.barn": "Lato: Pultti, Lankku, Ilmastointiteippi.",
    "materials.hint.silo": "Siilo: Naula, Ruuvi, Puupaneeli.",
    "materials.hint.expansion": "Laajennus: Lainhuutokirja, Nuija, Merkkipaalu.",
    "materials.target": "Tavoitekapasiteetti",
    "materials.target_ph": "esim. 1000 tai 1050",
    "materials.targetTool": "Tavoitetyökalu",
    "materials.target_ph_exp": "esim. 45",
    "materials.initial": "Alkuvarasto:",
    "materials.stock_ph": "täytä lomake suorittaaksesi jaon",
    "btn.calculate": "Laske",
    "btn.clear": "Tyhjennä",
    "btn.clear_tip": "Tyhjennä kaikki kentät",
    "btn.preset": "Esimerkki",
    "btn.preset_tip": "Nopea esimerkki",
    "kpi.perTool": "Tavoite per työkalu:",
    "kpi.balanced": "Tasapainossa ✓",
    "kpi.cap": "≤ 89/päivä ✓",
    "plan.title": "Jakelusuunnitelma",
    "plan.hint": "Päivittäiset jakelupaikat + päivittäinen seuranta. Päivän lopun määrät ovat täsmälleen samat.",
    "plan.day": "Päivä",
    "plan.used": "Käytetty",
    "plan.endTotal": "Loppusumma",
    "plan.each": "kutakin",
    "plan.sectionSlots": "📦 Jakelupaikat",
    "plan.sectionTracking": "📊 Päivittäinen seuranta (Tasapainossa jokaisen päivän lopussa)",
    "plan.policy": "Käytäntösuoja: jos jokin alkuvarastolomake on tyhjä, jakoa ei suoriteta; vain työkalukohtaiset vaatimukset näytetään.",
    "table.slot": "Paikka",
    "table.tool": "Työkalu",
    "table.amount": "Määrä",
    "table.total": "YHTEENSÄ",
    "table.start": "Alku",
    "table.added": "Lisätty",
    "table.remaining": "Jäljellä",
    "table.target": "Tavoite",
    "table.check": "Tarkista",
    "table.noDist": "Ei jakelua",
    "err.invalid": "Virheellinen! Täytä lomake jatkaaksesi.",
    "msg.enter": "Syötä alkuvarasto suorittaaksesi jaon.",
    "msg.expansionReq": "Jokainen työkalu vaatii <b>{n} esinettä</b> maan avaamiseksi.",
    "msg.upgradeReq": "Jokainen työkalu vaatii <b>{n} esinettä</b> päivittääkseen kapasiteetista {cap}.",
    "msg.generated": "Suunnitelma luotu {d} päivässä. Tasapainotettu päivittäin."
  },
  fr: {
    "title": "Outil d'amélioration - Hay Day",
    "subtitle": "Planifiez et calculez les articles nécessaires pour votre prochaine amélioration de capacité.",
    "tabs.barn": "GRANGE",
    "tabs.silo": "SILO",
    "tabs.expansion": "EXPANSION",
    "materials.title": "Matériaux",
    "materials.hint.barn": "Grange : Boulon, Planche, Ruban toilé.",
    "materials.hint.silo": "Silo : Clou, Vis, Panneau de bois.",
    "materials.hint.expansion": "Expansion : Acte de propriété, Maillet, Piquet de marquage.",
    "materials.target": "Capacité cible",
    "materials.target_ph": "ex: 1000 ou 1050",
    "materials.targetTool": "Outil cible",
    "materials.target_ph_exp": "ex: 45",
    "materials.initial": "Stock initial :",
    "materials.stock_ph": "entrez le formulaire pour effectuer la distribution",
    "btn.calculate": "Calculer",
    "btn.clear": "Effacer",
    "btn.clear_tip": "Effacer tous les champs",
    "btn.preset": "Exemple",
    "btn.preset_tip": "Exemple rapide",
    "kpi.perTool": "Cible par outil :",
    "kpi.balanced": "Équilibré ✓",
    "kpi.cap": "≤ 89/jour ✓",
    "plan.title": "Plan de distribution",
    "plan.hint": "Emplacements de distribution quotidiens + suivi quotidien. Les totaux en fin de journée sont exactement égaux.",
    "plan.day": "Jour",
    "plan.used": "Utilisé",
    "plan.endTotal": "Total final",
    "plan.each": "chacun",
    "plan.sectionSlots": "📦 Emplacements de distribution",
    "plan.sectionTracking": "📊 Suivi quotidien (Équilibré à la fin de chaque journée)",
    "plan.policy": "Règle de protection : si un formulaire de stock initial est vide, aucune distribution n'est exécutée ; seuls les besoins par outil sont affichés.",
    "table.slot": "Emplacement",
    "table.tool": "Outil",
    "table.amount": "Montant",
    "table.total": "TOTAL",
    "table.start": "Début",
    "table.added": "Ajouté",
    "table.remaining": "Restant",
    "table.target": "Cible",
    "table.check": "Vérifier",
    "table.noDist": "Pas de distribution",
    "err.invalid": "Invalide ! Veuillez entrer le formulaire pour continuer.",
    "msg.enter": "Entrez le stock initial pour effectuer la distribution.",
    "msg.expansionReq": "Chaque outil nécessite <b>{n} objets</b> pour débloquer le terrain.",
    "msg.upgradeReq": "Chaque outil nécessite <b>{n} objets</b> pour passer de la capacité {cap}.",
    "msg.generated": "Plan généré en {d} jour(s). Équilibré quotidiennement."
  },
  id: {
    "title": "Upgrade Tool - Hay Day",
    "subtitle": "Rencanakan dan hitung item yang diperlukan untuk upgrade kapasitas berikutnya.",
    "tabs.barn": "LUMBUNG",
    "tabs.silo": "SILO",
    "tabs.expansion": "PERLUASAN",
    "materials.title": "Material",
    "materials.hint.barn": "Lumbung: Baut, Papan, Lakban.",
    "materials.hint.silo": "Silo: Paku, Sekrup, Panel Kayu.",
    "materials.hint.expansion": "Ekspansi: Akta Tanah, Martil Kayu, Patok Tanah.",
    "materials.target": "Target Kapasitas",
    "materials.target_ph": "mis. 1000 atau 1050",
    "materials.targetTool": "Target alat",
    "materials.target_ph_exp": "mis. 45",
    "materials.initial": "Stok Awal:",
    "materials.stock_ph": "isi kolom untuk menjalankan distribusi",
    "btn.calculate": "Hitung",
    "btn.clear": "Hapus",
    "btn.clear_tip": "Hapus semua kolom",
    "btn.preset": "Contoh",
    "btn.preset_tip": "Contoh bawaan",
    "kpi.perTool": "Target per item:",
    "kpi.balanced": "Seimbang ✓",
    "kpi.cap": "≤ 89/hari ✓",
    "plan.title": "Rencana Distribusi",
    "plan.hint": "Slot distribusi harian + pelacakan harian. Total di akhir hari sama.",
    "plan.day": "Hari",
    "plan.used": "Terpakai",
    "plan.endTotal": "Total akhir",
    "plan.each": "masing-masing",
    "plan.sectionSlots": "📦 Slot Distribusi",
    "plan.sectionTracking": "📊 Pelacakan Harian (Sama rata di akhir setiap hari)",
    "plan.policy": "Aturan perlindungan: Jika form stok awal belum diisi, distribusi tidak akan dijalankan; hanya kebutuhan per alat yang akan ditampilkan.",
    "table.slot": "Slot",
    "table.tool": "Alat",
    "table.amount": "Jumlah",
    "table.total": "TOTAL",
    "table.start": "Awal",
    "table.added": "Tambah",
    "table.remaining": "Sisa",
    "table.target": "Target",
    "table.check": "Cek",
    "table.noDist": "Tidak ada distribusi",
    "err.invalid": "Tidak valid! Isi kolom untuk melanjutkan.",
    "msg.enter": "Masukkan stok awal untuk menjalankan distribusi.",
    "msg.expansionReq": "Setiap alat membutuhkan <b>{n} item</b> untuk membuka lahan.",
    "msg.upgradeReq": "Setiap alat membutuhkan <b>{n} item untuk upgrade dari kapasitas {cap}.</b>",
    "msg.generated": "Rencana dibuat dalam {d} hari. Seimbang per hari."
  },
  it: {
    "title": "Strumento di potenziamento - Hay Day",
    "subtitle": "Pianifica e calcola gli oggetti necessari per il tuo prossimo potenziamento di capacità.",
    "tabs.barn": "FIENILE",
    "tabs.silo": "SILO",
    "tabs.expansion": "ESPANSIONE",
    "materials.title": "Materiali",
    "materials.hint.barn": "Fienile: Bullone, Asse di legno, Nastro americano.",
    "materials.hint.silo": "Silo: Chiodo, Vite, Pannello di legno.",
    "materials.hint.expansion": "Espansione: Atto di proprietà, Mazza, Picchetto marcatore.",
    "materials.target": "Capacità target",
    "materials.target_ph": "es. 1000 o 1050",
    "materials.targetTool": "Strumento target",
    "materials.target_ph_exp": "es. 45",
    "materials.initial": "Scorta iniziale:",
    "materials.stock_ph": "inserisci il modulo per eseguire la distribuzione",
    "btn.calculate": "Calcola",
    "btn.clear": "Pulisci",
    "btn.clear_tip": "Pulisci tutti i campi",
    "btn.preset": "Esempio",
    "btn.preset_tip": "Esempio rapido",
    "kpi.perTool": "Target per strumento:",
    "kpi.balanced": "Bilanciato ✓",
    "kpi.cap": "≤ 89/giorno ✓",
    "plan.title": "Piano di distribuzione",
    "plan.hint": "Slot di distribuzione giornalieri + monitoraggio giornaliero. I conteggi di fine giornata sono esattamente uguali.",
    "plan.day": "Giorno",
    "plan.used": "Usato",
    "plan.endTotal": "Totale finale",
    "plan.each": "ciascuno",
    "plan.sectionSlots": "📦 Slot di distribuzione",
    "plan.sectionTracking": "📊 Monitoraggio giornaliero (Bilanciato alla fine di ogni giorno)",
    "plan.policy": "Regola di protezione: se un modulo di scorta iniziale è vuoto, non viene eseguita alcuna distribuzione; vengono mostrati solo i requisiti per strumento.",
    "table.slot": "Slot",
    "table.tool": "Strumento",
    "table.amount": "Quantità",
    "table.total": "TOTALE",
    "table.start": "Inizio",
    "table.added": "Aggiunto",
    "table.remaining": "Rimanente",
    "table.target": "Target",
    "table.check": "Controllo",
    "table.noDist": "Nessuna distribuzione",
    "err.invalid": "Non valido! Inserisci il modulo per procedere.",
    "msg.enter": "Inserisci la scorta iniziale per eseguire la distribuzione.",
    "msg.expansionReq": "Ogni strumento richiede <b>{n} oggetti</b> per sbloccare il terreno.",
    "msg.upgradeReq": "Ogni strumento richiede <b>{n} oggetti</b> per potenziare dalla capacità {cap}.",
    "msg.generated": "Piano generato in {d} giorno/i. Bilanciato giornalmente."
  },
  ja: {
    "title": "アップグレードツール - ヘイ・デイ",
    "subtitle": "次の容量アップグレードに必要なアイテムを計画し、計算します。",
    "tabs.barn": "納屋",
    "tabs.silo": "サイロ",
    "tabs.expansion": "拡張",
    "materials.title": "材料",
    "materials.hint.barn": "納屋：ボルト、板材、布テープ。",
    "materials.hint.silo": "サイロ：釘、ネジ、木の板。",
    "materials.hint.expansion": "拡張：土地の権利書、木槌、マーカー杭。",
    "materials.target": "目標容量",
    "materials.target_ph": "例：1000 または 1050",
    "materials.targetTool": "目標ツール",
    "materials.target_ph_exp": "例：45",
    "materials.initial": "初期在庫：",
    "materials.stock_ph": "フォームを入力して分配を実行します",
    "btn.calculate": "計算",
    "btn.clear": "クリア",
    "btn.clear_tip": "すべてのフィールドをクリア",
    "btn.preset": "プリセット",
    "btn.preset_tip": "簡単な例",
    "kpi.perTool": "ツールごとの目標：",
    "kpi.balanced": "バランス済み ✓",
    "kpi.cap": "≤ 89/日 ✓",
    "plan.title": "分配計画",
    "plan.hint": "毎日の分配スロット + 毎日の追跡。一日の終わりのカウントは完全に等しくなります。",
    "plan.day": "日",
    "plan.used": "使用済み",
    "plan.endTotal": "最終合計",
    "plan.each": "各",
    "plan.sectionSlots": "📦 分配スロット",
    "plan.sectionTracking": "📊 毎日の追跡（各日の終わりにバランス）",
    "plan.policy": "ポリシーガード：初期在庫フォームが空白の場合、分配は実行されません。ツールごとの要件のみが表示されます。",
    "table.slot": "スロット",
    "table.tool": "ツール",
    "table.amount": "量",
    "table.total": "合計",
    "table.start": "開始",
    "table.added": "追加済み",
    "table.remaining": "残り",
    "table.target": "目標",
    "table.check": "チェック",
    "table.noDist": "分配なし",
    "err.invalid": "無効です！続行するにはフォームを入力してください。",
    "msg.enter": "分配を実行するには初期在庫を入力してください。",
    "msg.expansionReq": "土地をアンロックするには、各ツールに<b>{n}個のアイテム</b>が必要です。",
    "msg.upgradeReq": "容量{cap}からアップグレードするには、各ツールに<b>{n}個のアイテム</b>が必要です。",
    "msg.generated": "{d}日で計画が生成されました。毎日バランスが取れています。"
  },
  ko: {
    "title": "업그레이드 도구 - 헤이데이",
    "subtitle": "다음 용량 업그레이드에 필요한 아이템을 계획하고 계산하세요.",
    "tabs.barn": "헛간",
    "tabs.silo": "사일로",
    "tabs.expansion": "확장",
    "materials.title": "재료",
    "materials.hint.barn": "헛간: 볼트, 판자, 접착 테이프.",
    "materials.hint.silo": "사일로: 못, 나사, 목재 패널.",
    "materials.hint.expansion": "확장: 토지 증서, 나무 망치, 말뚝.",
    "materials.target": "목표 용량",
    "materials.target_ph": "예: 1000 또는 1050",
    "materials.targetTool": "목표 도구",
    "materials.target_ph_exp": "예: 45",
    "materials.initial": "초기 재고:",
    "materials.stock_ph": "분배를 수행하려면 양식을 입력하세요",
    "btn.calculate": "계산",
    "btn.clear": "지우기",
    "btn.clear_tip": "모든 필드 지우기",
    "btn.preset": "예시",
    "btn.preset_tip": "빠른 예시",
    "kpi.perTool": "도구당 목표:",
    "kpi.balanced": "균형 ✓",
    "kpi.cap": "≤ 89/일 ✓",
    "plan.title": "분배 계획",
    "plan.hint": "일일 분배 슬롯 + 일일 추적. 하루 종료 시점의 개수는 정확히 동일합니다.",
    "plan.day": "일",
    "plan.used": "사용됨",
    "plan.endTotal": "최종 합계",
    "plan.each": "각각",
    "plan.sectionSlots": "📦 분배 슬롯",
    "plan.sectionTracking": "📊 일일 추적 (매일 종료 시점에 균형)",
    "plan.policy": "정책 보호: 초기 재고 양식이 비어 있으면 분배가 실행되지 않으며, 도구별 요구 사항만 표시됩니다.",
    "table.slot": "슬롯",
    "table.tool": "도구",
    "table.amount": "수량",
    "table.total": "총계",
    "table.start": "시작",
    "table.added": "추가됨",
    "table.remaining": "남은 수량",
    "table.target": "목표",
    "table.check": "확인",
    "table.noDist": "분배 없음",
    "err.invalid": "유효하지 않음! 계속하려면 양식을 입력하세요。",
    "msg.enter": "분배를 수행하려면 초기 재고를 입력하세요。",
    "msg.expansionReq": "토지를 잠금 해제하려면 각 도구에 <b>{n}개</b>의 아이템이 필요합니다。",
    "msg.upgradeReq": "용량 {cap}에서 업그레이드하려면 각 도구에 <b>{n}개</b>의 아이템이 필요합니다。",
    "msg.generated": "{d}일 만에 계획 생성. 매일 균형."
  },
  ms: {
    "title": "Alat Naik Taraf - Hay Day",
    "subtitle": "Rancang dan kira item yang diperlukan untuk naik taraf kapasiti anda yang seterusnya.",
    "tabs.barn": "BANGSAL",
    "tabs.silo": "SILO",
    "tabs.expansion": "PERLUASAN",
    "materials.title": "Bahan",
    "materials.hint.barn": "Bangsal: Bolt, Papan, Pita Kain.",
    "materials.hint.silo": "Silo: Paku, Skru, Panel Kayu.",
    "materials.hint.expansion": "Perluasan: Surat Ikatan Tanah, Tukul kayu, Penanda Tanah.",
    "materials.target": "Kapasiti Sasaran",
    "materials.target_ph": "cth, 1000 atau 1050",
    "materials.targetTool": "Alat sasaran",
    "materials.target_ph_exp": "cth, 45",
    "materials.initial": "Stok Awal:",
    "materials.stock_ph": "masukkan borang untuk melaksanakan pengedaran",
    "btn.calculate": "Kira",
    "btn.clear": "Padam",
    "btn.clear_tip": "Padam semua medan",
    "btn.preset": "Contoh",
    "btn.preset_tip": "Contoh cepat",
    "kpi.perTool": "Sasaran setiap alat:",
    "kpi.balanced": "Seimbang ✓",
    "kpi.cap": "≤ 89/hari ✓",
    "plan.title": "Pelan Pengedaran",
    "plan.hint": "Slot pengedaran harian + penjejakan harian. Kiraan akhir hari adalah sama.",
    "plan.day": "Hari",
    "plan.used": "Digunakan",
    "plan.endTotal": "Jumlah akhir",
    "plan.each": "setiap",
    "plan.sectionSlots": "📦 Slot Pengedaran",
    "plan.sectionTracking": "📊 Penjejakan Harian (Seimbang pada akhir setiap hari)",
    "plan.policy": "Perlindungan dasar: jika mana-mana borang stok awal kosong, tiada pengedaran dilaksanakan; hanya keperluan setiap alat ditunjukkan.",
    "table.slot": "Slot",
    "table.tool": "Alat",
    "table.amount": "Jumlah",
    "table.total": "JUMLAH",
    "table.start": "Mula",
    "table.added": "Ditambah",
    "table.remaining": "Baki",
    "table.target": "Sasaran",
    "table.check": "Semak",
    "table.noDist": "Tiada pengedaran",
    "err.invalid": "Tidak sah! Sila masukkan borang untuk meneruskan.",
    "msg.enter": "Masukkan stok awal untuk melaksanakan pengedaran.",
    "msg.expansionReq": "Setiap alat memerlukan <b>{n} item</b> untuk membuka kunci tanah.",
    "msg.upgradeReq": "Setiap alat memerlukan <b>{n} item</b> untuk menaik taraf dari kapasiti {cap}.",
    "msg.generated": "Pelan dihasilkan dalam {d} hari. Seimbang setiap hari."
  },
  nl: {
    "title": "Upgrade Tool - Hay Day",
    "subtitle": "Plan en bereken de items die nodig zijn voor je volgende capaciteitsupgrade.",
    "tabs.barn": "SCHUUR",
    "tabs.silo": "SILO",
    "tabs.expansion": "UITBREIDING",
    "materials.title": "Materialen",
    "materials.hint.barn": "Schuur: Bout, Plank, Plakband.",
    "materials.hint.silo": "Silo: Spijker, Schroef, Houten Paneel.",
    "materials.hint.expansion": "Uitbreiding: Koopakte, Hamer, Markeringspaal.",
    "materials.target": "Doelcapaciteit",
    "materials.target_ph": "bijv. 1000 of 1050",
    "materials.targetTool": "Doelgereedschap",
    "materials.target_ph_exp": "bijv. 45",
    "materials.initial": "Beginvoorraad:",
    "materials.stock_ph": "voer het formulier in om de distributie uit te voeren",
    "btn.calculate": "Bereken",
    "btn.clear": "Wissen",
    "btn.clear_tip": "Alle velden wissen",
    "btn.preset": "Voorbeeld",
    "btn.preset_tip": "Snel voorbeeld",
    "kpi.perTool": "Doel per gereedschap:",
    "kpi.balanced": "Gebalanceerd ✓",
    "kpi.cap": "≤ 89/dag ✓",
    "plan.title": "Distributieplan",
    "plan.hint": "Dagelijkse distributieslots + dagelijkse tracking. De tellingen aan het einde van de dag zijn exact gelijk.",
    "plan.day": "Dag",
    "plan.used": "Gebruikt",
    "plan.endTotal": "Eindtotaal",
    "plan.each": "elk",
    "plan.sectionSlots": "📦 Distributieslots",
    "plan.sectionTracking": "📊 Dagelijkse tracking (Gebalanceerd aan het einde van elke dag)",
    "plan.policy": "Beleidsbescherming: als een formulier voor de beginvoorraad leeg is, wordt er geen distributie uitgevoerd; alleen de vereisten per gereedschap worden getoond.",
    "table.slot": "Slot",
    "table.tool": "Gereedschap",
    "table.amount": "Aantal",
    "table.total": "TOTAAL",
    "table.start": "Start",
    "table.added": "Toegevoegd",
    "table.remaining": "Resterend",
    "table.target": "Doel",
    "table.check": "Controle",
    "table.noDist": "Geen distributie",
    "err.invalid": "Ongeldig! Voer het formulier in om door te gaan.",
    "msg.enter": "Voer de beginvoorraad in om de distributie uit te voeren.",
    "msg.expansionReq": "Elk gereedschap vereist <b>{n} items</b> om het land te ontgrendelen.",
    "msg.upgradeReq": "Elk gereedschap vereist <b>{n} items</b> om te upgraden vanaf capaciteit {cap}.",
    "msg.generated": "Plan gegenereerd in {d} dag(en). Dagelijks gebalanceerd."
  },
  no: {
    "title": "Oppgraderingsverktøy - Hay Day",
    "subtitle": "Planlegg og beregn gjenstandene som kreves for din neste kapasitetsoppgradering.",
    "tabs.barn": "LÅVE",
    "tabs.silo": "SILO",
    "tabs.expansion": "UTVIDELSE",
    "materials.title": "Materialer",
    "materials.hint.barn": "Låve: Bolt, Planke, Gaffateip.",
    "materials.hint.silo": "Silo: Spiker, Skrue, Trepanel.",
    "materials.hint.expansion": "Utvidelse: Skjøte, Slegge, Markeringsstake.",
    "materials.target": "Målkapasitet",
    "materials.target_ph": "f.eks. 1000 eller 1050",
    "materials.targetTool": "Målverktøy",
    "materials.target_ph_exp": "f.eks. 45",
    "materials.initial": "Startbeholdning:",
    "materials.stock_ph": "fyll inn skjemaet for å utføre distribusjon",
    "btn.calculate": "Beregn",
    "btn.clear": "Tøm",
    "btn.clear_tip": "Tøm alle felt",
    "btn.preset": "Eksempel",
    "btn.preset_tip": "Raskt eksempel",
    "kpi.perTool": "Mål per verktøy:",
    "kpi.balanced": "Balansert ✓",
    "kpi.cap": "≤ 89/dag ✓",
    "plan.title": "Distribusjonsplan",
    "plan.hint": "Daglige distribusjonsplasser + daglig sporing. Slutt-tellingene er nøyaktig like.",
    "plan.day": "Dag",
    "plan.used": "Brukt",
    "plan.endTotal": "Sluttsum",
    "plan.each": "hver",
    "plan.sectionSlots": "📦 Distribusjonsplasser",
    "plan.sectionTracking": "📊 Daglig sporing (Balansert ved slutten av hver dag)",
    "plan.policy": "Retningslinjebeskyttelse: hvis et skjema for startbeholdning er tomt, utføres ingen distribusjon; bare kravene per verktøy vises.",
    "table.slot": "Plass",
    "table.tool": "Verktøy",
    "table.amount": "Antall",
    "table.total": "TOTALT",
    "table.start": "Start",
    "table.added": "Lagt til",
    "table.remaining": "Gjenværende",
    "table.target": "Mål",
    "table.check": "Sjekk",
    "table.noDist": "Ingen distribusjon",
    "err.invalid": "Ugyldig! Vennligst fyll inn skjemaet for å fortsette.",
    "msg.enter": "Angi startbeholdningen for å utføre distribusjon.",
    "msg.expansionReq": "Hvert verktøy krever <b>{n} gjenstander</b> for å låse opp landet.",
    "msg.upgradeReq": "Hvert verktøy krever <b>{n} gjenstander</b> for å oppgradere fra kapasitet {cap}.",
    "msg.generated": "Plan generert på {d} dag(er). Balansert daglig."
  },
  pt: {
    "title": "Ferramenta de Melhoria - Hay Day",
    "subtitle": "Planeje e calcule os itens necessários para sua próxima melhoria de capacidade.",
    "tabs.barn": "CELEIRO",
    "tabs.silo": "SILO",
    "tabs.expansion": "EXPANSÃO",
    "materials.title": "Materiais",
    "materials.hint.barn": "Celeiro: Parafuso sextavado, Tábua, Fita de Pano.",
    "materials.hint.silo": "Silo: Prego, Parafuso, Painel de Madeira.",
    "materials.hint.expansion": "Expansão: Escritura de Terra, Marreta, Estaca de Marcação.",
    "materials.target": "Capacidade Alvo",
    "materials.target_ph": "ex: 1000 ou 1050",
    "materials.targetTool": "Ferramenta Alvo",
    "materials.target_ph_exp": "ex: 45",
    "materials.initial": "Estoque Inicial:",
    "materials.stock_ph": "preencha o formulário para realizar a distribuição",
    "btn.calculate": "Calcular",
    "btn.clear": "Limpar",
    "btn.clear_tip": "Limpar todos os campos",
    "btn.preset": "Exemplo",
    "btn.preset_tip": "Exemplo rápido",
    "kpi.perTool": "Meta por ferramenta:",
    "kpi.balanced": "Balanceado ✓",
    "kpi.cap": "≤ 89/dia ✓",
    "plan.title": "Plano de Distribuição",
    "plan.hint": "Espaços de distribuição diários + acompanhamento diário. As contagens no final do dia são exatamente iguais.",
    "plan.day": "Dia",
    "plan.used": "Usado",
    "plan.endTotal": "Total final",
    "plan.each": "cada",
    "plan.sectionSlots": "📦 Espaços de Distribuição",
    "plan.sectionTracking": "📊 Acompanhamento Diário (Balanceado no final de cada dia)",
    "plan.policy": "Proteção de política: se algum formulário de estoque inicial estiver em branco, nenhuma distribuição será executada; apenas os requisitos por ferramenta são mostrados.",
    "table.slot": "Espaço",
    "table.tool": "Ferramenta",
    "table.amount": "Quantidade",
    "table.total": "TOTAL",
    "table.start": "Início",
    "table.added": "Adicionado",
    "table.remaining": "Restante",
    "table.target": "Meta",
    "table.check": "Verificar",
    "table.noDist": "Sem distribuição",
    "err.invalid": "Inválido! Por favor, preencha o formulário para continuar.",
    "msg.enter": "Insira o estoque inicial para realizar a distribuição.",
    "msg.expansionReq": "Cada ferramenta requer <b>{n} itens</b> para desbloquear o terreno.",
    "msg.upgradeReq": "Cada ferramenta requer <b>{n} itens</b> para melhorar da capacidade {cap}.",
    "msg.generated": "Plano gerado em {d} dia(s). Balanceado diariamente."
  },
  ru: {
    "title": "Инструмент для улучшения - Hay Day",
    "subtitle": "Планируйте и рассчитывайте предметы, необходимые для следующего улучшения вместимости.",
    "tabs.barn": "АМБАР",
    "tabs.silo": "СИЛОС",
    "tabs.expansion": "РАСШИРЕНИЕ",
    "materials.title": "Материалы",
    "materials.hint.barn": "Амбар: Болт, Доска, Армированный скотч.",
    "materials.hint.silo": "Силос: Гвоздь, Шуруп, Деревянная панель.",
    "materials.hint.expansion": "Расширение: Документ на землю, Киянка, Межевой кол.",
    "materials.target": "Целевая вместимость",
    "materials.target_ph": "например, 1000 или 1050",
    "materials.targetTool": "Целевой инструмент",
    "materials.target_ph_exp": "например, 45",
    "materials.initial": "Начальный запас:",
    "materials.stock_ph": "заполните форму для выполнения распределения",
    "btn.calculate": "Рассчитать",
    "btn.clear": "Очистить",
    "btn.clear_tip": "Очистить все поля",
    "btn.preset": "Пример",
    "btn.preset_tip": "Быстрый пример",
    "kpi.perTool": "Цель на инструмент:",
    "kpi.balanced": "Сбалансировано ✓",
    "kpi.cap": "≤ 89/день ✓",
    "plan.title": "План распределения",
    "plan.hint": "Ежедневные слоты распределения + ежедневное отслеживание. Количество на конец дня точно совпадает.",
    "plan.day": "День",
    "plan.used": "Использовано",
    "plan.endTotal": "Итого",
    "plan.each": "каждый",
    "plan.sectionSlots": "📦 Слоты распределения",
    "plan.sectionTracking": "📊 Ежедневное отслеживание (сбалансировано к концу каждого дня)",
    "plan.policy": "Защита политики: если любая форма начального запаса пуста, распределение не выполняется; отображаются только требования для каждого инструмента.",
    "table.slot": "Слот",
    "table.tool": "Инструмент",
    "table.amount": "Количество",
    "table.total": "ИТОГО",
    "table.start": "Начало",
    "table.added": "Добавлено",
    "table.remaining": "Осталось",
    "table.target": "Цель",
    "table.check": "Проверка",
    "table.noDist": "Нет распределения",
    "err.invalid": "Неверно! Пожалуйста, заполните форму для продолжения.",
    "msg.enter": "Введите начальный запас для выполнения распределения.",
    "msg.expansionReq": "Каждый инструмент требует <b>{n} предметов</b>, чтобы разблокировать землю.",
    "msg.upgradeReq": "Каждый инструмент требует <b>{n} предметов</b> для улучшения с вместимости {cap}.",
    "msg.generated": "План сгенерирован за {d} день(дней). Ежедневно сбалансировано."
  },
  sv: {
    "title": "Uppgraderingsverktyg - Hay Day",
    "subtitle": "Planera och beräkna de föremål som krävs för din nästa kapacitetsuppgradering.",
    "tabs.barn": "LADA",
    "tabs.silo": "SILO",
    "tabs.expansion": "EXPANSION",
    "materials.title": "Material",
    "materials.hint.barn": "Lada: Bult, Planka, Silvertejp.",
    "materials.hint.silo": "Silo: Spik, Skruv, Träpanel.",
    "materials.hint.expansion": "Expansion: Lagfart, Klubb, Markeringspinne.",
    "materials.target": "Målkapacitet",
    "materials.target_ph": "t.ex. 1000 eller 1050",
    "materials.targetTool": "Målverktyg",
    "materials.target_ph_exp": "t.ex. 45",
    "materials.initial": "Startlager:",
    "materials.stock_ph": "fyll i formuläret för att utföra distribution",
    "btn.calculate": "Beräkna",
    "btn.clear": "Rensa",
    "btn.clear_tip": "Rensa alla fält",
    "btn.preset": "Exempel",
    "btn.preset_tip": "Snabbt exempel",
    "kpi.perTool": "Mål per verktyg:",
    "kpi.balanced": "Balanserat ✓",
    "kpi.cap": "≤ 89/dag ✓",
    "plan.title": "Distributionsplan",
    "plan.hint": "Dagliga distributionsplatser + daglig spårning. Antalet vid dagens slut är exakt lika.",
    "plan.day": "Dag",
    "plan.used": "Använt",
    "plan.endTotal": "Slutsumma",
    "plan.each": "vardera",
    "plan.sectionSlots": "📦 Distributionsplatser",
    "plan.sectionTracking": "📊 Daglig spårning (Balanserat vid slutet av varje dag)",
    "plan.policy": "Policyskydd: om något startlagerformulär är tomt, utförs ingen distribution; endast kraven per verktyg visas.",
    "table.slot": "Plats",
    "table.tool": "Verktyg",
    "table.amount": "Antal",
    "table.total": "TOTALT",
    "table.start": "Start",
    "table.added": "Tillagt",
    "table.remaining": "Återstående",
    "table.target": "Mål",
    "table.check": "Kontroll",
    "table.noDist": "Ingen distribution",
    "err.invalid": "Ogiltig! Vänligen fyll i formuläret för att fortsätta.",
    "msg.enter": "Ange startlagret för att utföra distributionen.",
    "msg.expansionReq": "Varje verktyg kräver <b>{n} föremål</b> för att låsa upp marken.",
    "msg.upgradeReq": "Varje verktyg kräver <b>{n} föremål</b> för att uppgradera från kapacitet {cap}.",
    "msg.generated": "Plan genererad på {d} dag(ar). Balanserat dagligen."
  },
  th: {
    "title": "เครื่องมืออัปเกรด - Hay Day",
    "subtitle": "วางแผนและคำนวณไอเท็มที่จำเป็นสำหรับการอัปเกรดความจุครั้งต่อไปของคุณ",
    "tabs.barn": "โรงนา",
    "tabs.silo": "ไซโล",
    "tabs.expansion": "การขยายพื้นที่",
    "materials.title": "วัสดุ",
    "materials.hint.barn": "โรงนา: โบลต์, แผ่นไม้, เทปกาว",
    "materials.hint.silo": "ไซโล: ตะปู, สกรู, แผงไม้",
    "materials.hint.expansion": "การขยายพื้นที่: โฉนดที่ดิน, ค้อนไม้, หลักหมุด",
    "materials.target": "ความจุเป้าหมาย",
    "materials.target_ph": "เช่น 1000 หรือ 1050",
    "materials.targetTool": "เครื่องมือเป้าหมาย",
    "materials.target_ph_exp": "เช่น 45",
    "materials.initial": "สต็อกเริ่มต้น:",
    "materials.stock_ph": "กรอกแบบฟอร์มเพื่อทำการแจกจ่าย",
    "btn.calculate": "คำนวณ",
    "btn.clear": "ล้าง",
    "btn.clear_tip": "ล้างทุกช่อง",
    "btn.preset": "ตัวอย่าง",
    "btn.preset_tip": "ตัวอย่างรวดเร็ว",
    "kpi.perTool": "เป้าหมายต่อเครื่องมือ:",
    "kpi.balanced": "สมดุล ✓",
    "kpi.cap": "≤ 89/วัน ✓",
    "plan.title": "แผนการแจกจ่าย",
    "plan.hint": "ช่องแจกจ่ายรายวัน + การติดตามรายวัน จำนวน ณ สิ้นวันจะเท่ากันพอดี",
    "plan.day": "วัน",
    "plan.used": "ใช้แล้ว",
    "plan.endTotal": "ยอดรวมสิ้นสุด",
    "plan.each": "แต่ละ",
    "plan.sectionSlots": "📦 ช่องการแจกจ่าย",
    "plan.sectionTracking": "📊 การติดตามรายวัน (สมดุล ณ สิ้นสุดของแต่ละวัน)",
    "plan.policy": "การป้องกันนโยบาย: หากแบบฟอร์มสต็อกเริ่มต้นใดว่างเปล่า จะไม่มีการแจกจ่ายใดๆ เกิดขึ้น จะแสดงเฉพาะข้อกำหนดต่อเครื่องมือเท่านั้น",
    "table.slot": "ช่อง",
    "table.tool": "เครื่องมือ",
    "table.amount": "จำนวน",
    "table.total": "ทั้งหมด",
    "table.start": "เริ่มต้น",
    "table.added": "เพิ่มแล้ว",
    "table.remaining": "ที่เหลือ",
    "table.target": "เป้าหมาย",
    "table.check": "ตรวจสอบ",
    "table.noDist": "ไม่มีการแจกจ่าย",
    "err.invalid": "ไม่ถูกต้อง! กรุณากรอกแบบฟอร์มเพื่อดำเนินการต่อ",
    "msg.enter": "ป้อนสต็อกเริ่มต้นเพื่อทำการแจกจ่าย",
    "msg.expansionReq": "แต่ละเครื่องมือต้องการ <b>{n} ชิ้น</b> เพื่อปลดล็อกที่ดิน",
    "msg.upgradeReq": "แต่ละเครื่องมือต้องการ <b>{n} ชิ้น</b> เพื่ออัปเกรดจากความจุ {cap}",
    "msg.generated": "แผนสร้างขึ้นใน {d} วัน สมดุลรายวัน"
  },
  tr: {
    "title": "Yükseltme Aracı - Hay Day",
    "subtitle": "Bir sonraki kapasite yükseltmeniz için gereken öğeleri planlayın ve hesaplayın.",
    "tabs.barn": "AMBAR",
    "tabs.silo": "SİLO",
    "tabs.expansion": "GENİŞLETME",
    "materials.title": "Malzemeler",
    "materials.hint.barn": "Ambar: Civata, Kalas, Koli Bandı.",
    "materials.hint.silo": "Silo: Çivi, Vida, Ahşap Panel.",
    "materials.hint.expansion": "Genişletme: Arazi Senedi, Tokmak, İşaret Kazığı.",
    "materials.target": "Hedef Kapasite",
    "materials.target_ph": "örn. 1000 veya 1050",
    "materials.targetTool": "Hedef alet",
    "materials.target_ph_exp": "örn. 45",
    "materials.initial": "Başlangıç Stoğu:",
    "materials.stock_ph": "dağıtımı gerçekleştirmek için formu doldurun",
    "btn.calculate": "Hesapla",
    "btn.clear": "Temizle",
    "btn.clear_tip": "Tüm alanları temizle",
    "btn.preset": "Örnek",
    "btn.preset_tip": "Hızlı örnek",
    "kpi.perTool": "Alet başına hedef:",
    "kpi.balanced": "Dengeli ✓",
    "kpi.cap": "≤ 89/gün ✓",
    "plan.title": "Dağıtım Planı",
    "plan.hint": "Günlük dağıtım yuvaları + günlük takip. Gün sonu sayıları tam olarak eşittir.",
    "plan.day": "Gün",
    "plan.used": "Kullanılan",
    "plan.endTotal": "Son toplam",
    "plan.each": "her biri",
    "plan.sectionSlots": "📦 Dağıtım Yuvaları",
    "plan.sectionTracking": "📊 Günlük Takip (Her günün sonunda dengelenir)",
    "plan.policy": "Politika koruması: herhangi bir başlangıç stoku formu boşsa, dağıtım yapılmaz; sadece alet başına gereksinimler gösterilir.",
    "table.slot": "Yuva",
    "table.tool": "Alet",
    "table.amount": "Miktar",
    "table.total": "TOPLAM",
    "table.start": "Başlangıç",
    "table.added": "Eklendi",
    "table.remaining": "Kalan",
    "table.target": "Hedef",
    "table.check": "Kontrol",
    "table.noDist": "Dağıtım yok",
    "err.invalid": "Geçersiz! Lütfen devam etmek için formu doldurun.",
    "msg.enter": "Dağıtımı gerçekleştirmek için başlangıç stoğunu girin.",
    "msg.expansionReq": "Her alet, araziyi açmak için <b>{n} öğe</b> gerektirir.",
    "msg.upgradeReq": "Her alet, kapasite {cap}'den yükseltmek için <b>{n} öğe</b> gerektirir.",
    "msg.generated": "Plan {d} gün içinde oluşturuldu. Günlük olarak dengeli."
  },
  vi: {
    "title": "Công cụ Nâng cấp - Hay Day",
    "subtitle": "Lập kế hoạch và tính toán các vật phẩm cần thiết cho lần nâng cấp sức chứa tiếp theo của bạn.",
    "tabs.barn": "NHÀ KHO",
    "tabs.silo": "SILO",
    "tabs.expansion": "MỞ RỘNG",
    "materials.title": "Vật liệu",
    "materials.hint.barn": "Nhà kho: Bu lông, Ván gỗ, Băng keo.",
    "materials.hint.silo": "Silo: Đinh, Ốc vít, Tấm gỗ.",
    "materials.hint.expansion": "Mở rộng: Giấy tờ đất, Búa gỗ, Cọc đánh dấu.",
    "materials.target": "Sức chứa mục tiêu",
    "materials.target_ph": "ví dụ: 1000 hoặc 1050",
    "materials.targetTool": "Công cụ mục tiêu",
    "materials.target_ph_exp": "ví dụ: 45",
    "materials.initial": "Tồn kho ban đầu:",
    "materials.stock_ph": "nhập biểu mẫu để thực hiện phân phối",
    "btn.calculate": "Tính toán",
    "btn.clear": "Xóa",
    "btn.clear_tip": "Xóa tất cả các trường",
    "btn.preset": "Ví dụ",
    "btn.preset_tip": "Ví dụ nhanh",
    "kpi.perTool": "Mục tiêu mỗi công cụ:",
    "kpi.balanced": "Cân bằng ✓",
    "kpi.cap": "≤ 89/ngày ✓",
    "plan.title": "Kế hoạch phân phối",
    "plan.hint": "Các ô phân phối hàng ngày + theo dõi hàng ngày. Số lượng cuối ngày hoàn toàn bằng nhau.",
    "plan.day": "Ngày",
    "plan.used": "Đã dùng",
    "plan.endTotal": "Tổng cuối",
    "plan.each": "mỗi",
    "plan.sectionSlots": "📦 Ô phân phối",
    "plan.sectionTracking": "📊 Theo dõi hàng ngày (Cân bằng vào cuối mỗi ngày)",
    "plan.policy": "Bảo vệ chính sách: jika bất kỳ biểu mẫu tồn kho ban đầu nào trống, không có phân phối nào được thực hiện; chỉ hiển thị các yêu cầu cho mỗi công cụ.",
    "table.slot": "Ô",
    "table.tool": "Công cụ",
    "table.amount": "Số lượng",
    "table.total": "TỔNG",
    "table.start": "Bắt đầu",
    "table.added": "Đã thêm",
    "table.remaining": "Còn lại",
    "table.target": "Mục tiêu",
    "table.check": "Kiểm tra",
    "table.noDist": "Không có phân phối",
    "err.invalid": "Không hợp lệ! Vui lòng nhập biểu mẫu để tiếp tục.",
    "msg.enter": "Nhập tồn kho ban đầu để thực hiện phân phối.",
    "msg.expansionReq": "Mỗi công cụ yêu cầu <b>{n} vật phẩm</b> để mở khóa đất.",
    "msg.upgradeReq": "Mỗi công cụ yêu cầu <b>{n} vật phẩm</b> để nâng cấp từ sức chứa {cap}.",
    "msg.generated": "Kế hoạch được tạo trong {d} ngày. Cân bằng hàng ngày."
  }
};
